# Generated by Django 3.0.6 on 2020-05-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('link_anh_dai_dien', models.CharField(max_length=200)),
                ('ngay_sinh', models.DateField()),
                ('ngay_tao', models.DateField()),
            ],
        ),
    ]
